blog/urls.py
#todas las paginas para el blog
from django.urls import path
#from django.views import render_post
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('',render_posts, name='posts'),
    path('<int:post_id>', post_detail,name='post_detail'), #para mostrar distintos posts desde vista especial
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include #include para incluir carpeta como blog
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls') ),
]

#pattern para mostrar estaticos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
#from django.db.models.fields import CharField, URLField
#from django.db.models.fields.files import ImageField
import datetime
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/iamges/')
    date = models.DateField(datetime.date.today)

    def __str__(self):
        return self.title + ' - ' + self.description

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

# Create your models here.
class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/iamges/')
    url = URLField(blank=True)

    def __str__(self):
        return self.title + ' - ' + self.description

blog/views.py
from django.shortcuts import render, get_object_or_404
from.models import Post
# Create your views here.
def render_posts(request):
  # posts = Post.objects.all()
   total_posts = Post.objects.count()
   posts = Post.objects.order_by("-date")
   return render(request,'posts.html',{'posts':posts,"total_posts": total_posts})

def post_detail(request, post_id):
   post=get_object_or_404(Post,pk=post_id)
   return render(request,'post_detail.html',{"post":post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here. #render conoce la carpeta templates comentario
def home(request):
    projects =  Project.objects.all() #proyectos en la base de datos
    return render(request,'home.html', {'projects':projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}

<div class="text-center">

    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>
  
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
  
  
    <div class="my-4">
  
    {{post.description|safe}}
    </div>
  </div>
<!-- <h1>Post</h1>

<h2>{{post.title}}</h2>

<p>{{post.description|safe}</p>
<img src="{{post.image.url}}" alt="{{post.title}}"> -->

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}

<h1 class="fs-2">Posts</h1>
<h3>There are {{total_posts}} post{{total_posts|pluralize}}</h3>


{% for post in posts %}

<div class="py-3">

    <div class="card card-body bg-black">
      <div class="row">
  
        <div class="col-3">
          <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">
  
        </div>
        <div class="col-9">
  
          <h1>{{post.title}}</h1>
          <p>{{post.description|striptags|truncatechars:150}}</p>
          <p>{{post.date|date:'M d Y'|upper}}</p>
  
          <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-sm">{{post.title}}</a>
        </div>
      </div>
    </div>
  </div>
<!-- <h2>{{post.title}}</h2>

<div class="card card-body">
    <div class="row">
        <div class="col-3">

        </div>
        <img src="{{post.image.url}}" alt="{{post.title}}">

    </div>


<p>{{post.description|striptags|truncatechars:150}}</p>
<p>{{post.date|date:'M d Y'|upper}}</p>


<a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>

</div> -->


{% endfor %}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black">
<div class="col-md-4 my-auto p-4">
<img src="{% static 'portfolio/YO.png'%} " >
</div>

<div class="col-md-8 my-auto p-4">
    <h1>I am <strong>Santiago Kesler</strong></h1>
    <h3>I'm a Python back-end Developer</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis tempora perspiciatis molestias iusto ducimus
      soluta mollitia ratione, fuga praesentium, reiciendis minima! Facere, veniam! Omnis, quod molestias quo fugit enim
      vero vitae, cumque tenetur at, impedit provident dicta laudantium quia facilis consequuntur blanditiis iste
      laborum voluptatibus libero doloribus? Pariatur voluptatem obcaecati deserunt aperiam exercitationem nam voluptas
      rerum reprehenderit minima, earum impedit saepe eos ducimus fugit itaque a nulla omnis architecto laudantium
      blanditiis? Eius ipsum quidem enim architecto fugiat porro inventore libero praesentium aperiam nulla
      exercitationem nemo soluta, culpa impedit est et doloribus ut necessitatibus odit, dicta voluptate! Vero ab nulla
      placeat.</p>
    <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Download CV</a>
  </div>
</header>

<!-- Porfolio Section -->
<div class="row my-4 text-center">

    <h3>My Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, aperiam?</p>
  
    {% for project in projects %}
    <div class="col-md-4 p-4">
      <div class="card bg-black card-project">
        <img src="{{project.image.url }}" class="card-img-top" />
  
        <div class="card-body">
  
          <h2>{{ project.title }}</h2>
          <p>{{ project.description }}</p>
  
          {% if project.url %}
          <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">Visit the
            Project</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>


    <!-- {% for project in projects %}

    <h2>{{project.title}}</h2>
    <p>{{project.description}}</p>
    <img src="{{project.image.url}}" alt="{{project.title}}">

    {% if project.url %}
    <a href="{{project.url}}">{{project.url}}</a>
    {% endif %}

    {% endfor %} -->

{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    
    {% include 'partials/navbar.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <div class="container p-4">
    {% block content %}
    {% endblock %}
    </div>
    <!-- <footer>Footer</footer> -->
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Santiago Portfolio</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
          <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
          <!-- <a class="nav-link" href="/blog">Blog</a> o se puede hacer con django url-->
          <a class="nav-link" href="{% url  'blog:posts' %}">Blog</a> 
          <!-- 'blog':posts cuando click en blog mandar a post -->
          <a class="btn btn-primary btn-sm d-flex align-items-center" href="{% static 'portfolio/CV.pdf' %}" target="_blank">Download CV</a>
          <!-- <a class="nav-link disabled">Disabled</a> -->
        </div>
      </div>
    </div>
  </nav>